# This is a basic workflow to help you get started with Actions

name: Build

on:  
  push:
  pull_request:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-15
    
    steps:
      - uses: actions/checkout@v3
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.0
  
      - name: Install swiftformat
        run: brew install swiftformat

      - name: pod install
        run: make pod-install
         
      - name: Linting
        run: make lint
  
      - name: Run tests
        run: make test
  
      # - name: Upload Code Coverage 
      #   uses: codecov/codecov-action@v3
      #   with:
      #     verbose: true
      #     name: aep-notificationcontent-ios
      #     move_coverage_to_trash: true
